/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ebenlib;
import org.ebenlib.cli.CommandRouter;


public class App {
    public String getGreeting() {
        return "Ebenezer Library System!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        CommandRouter.route(args);
    }
}
